name: Project Publishing
on:
  push:
    paths: [ 'WpfUi/**','**/Publish.yml' ]
permissions:
  contents: read
jobs:
  publish:
    strategy:
      matrix:
        config:
          - name: "single-file"
            args: "-p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:SatelliteResourceLanguages=."
          - name: "ready-to-run"
            args: "-p:PublishReadyToRun=true -p:PublishReadyToRunComposite=true"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@main
        with:
          path: ~/.nuget/packages
          key: nuget-cache
      - run: dotnet publish -r win-x64 ${{ matrix.config.args }}
      - uses: actions/upload-artifact@main
        with:
          name: Release-${{ matrix.config.name }}
          path: '**/publish'
